version: '3.8'

services:
  web:
    build: ./main
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./main/:/usr/src/main/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
    - db

  next-src:
    build:
      context: ./next-src
      dockerfile: Dockerfile
      # target: runner
    # volumes:
    #   ./next-src:/usr/src/next-src
    command: yarn dev
    ports:
      - 3000:3000
    env_file:
      - ./next-src/.env
    depends_on:
      - web

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: