version: '3.8'

services:
  web:
    build:
      context: ./main
      dockerfile: Dockerfile.prod
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/main/web/staticfiles
    ports:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  # next-src:
  #   build:
  #     context: ./next-src
  #     dockerfile: Dockerfile
  #     target: runner
  #   # volumes:
  #   #   ./next-src:/usr/src/next-src
  #   command: yarn dev
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - ./next-src/.env
  #   depends_on:
  #     - web
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/main/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: